<!doctype html>
<html lang="zh-CN">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="color-scheme" content="light dark">
<title>去水印解析 · 短视频工具</title>
<link rel="icon" href="data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 32 32'%3E%3Crect width='32' height='32' rx='7' fill='%231b4a49'/%3E%3Cpath d='M9 9h6v6H9zM17 17h6v6h-6zM17 9h6v6h-6zM9 17h6v6H9z' fill='%23f5c85d'/%3E%3C/svg%3E">
<style>
:root{--bg:#eef0eb;--paper:#fff;--soft:#f7f9f4;--warm:#fbfaf5;--ink:#1b2630;--muted:#68736e;--faint:#96a19b;--line:#d9ded7;--strong:#c3cbc2;--teal:#1b4a49;--teal-dark:#123b3b;--teal-soft:#e8f1ee;--coral:#d86145;--coral-dark:#ae452f;--coral-soft:#fff0eb;--yellow:#f5c85d;--danger:#b8443e;--danger-soft:#fff0ee;--shadow:0 14px 36px rgba(24,39,34,.08);--small-shadow:0 5px 16px rgba(24,39,34,.06);--r:8px;--motion:.2s ease}
:root.dark{--bg:#152220;--paper:#1d2d2a;--soft:#20332f;--warm:#26352f;--ink:#f3f5ef;--muted:#b4c0b8;--faint:#82928a;--line:#38504a;--strong:#4b625b;--teal:#a8d3c6;--teal-dark:#d8eee4;--teal-soft:#29463f;--coral:#f28a6d;--coral-dark:#ffad95;--coral-soft:#4a302c;--yellow:#f5cf73;--danger:#ff9a8b;--danger-soft:#4d2e2b;--shadow:0 16px 38px rgba(0,0,0,.2);--small-shadow:0 5px 16px rgba(0,0,0,.16)}
@media(prefers-reduced-motion:reduce){*,*::before,*::after{animation-duration:.01ms!important;transition-duration:.01ms!important}}
*{box-sizing:border-box}[hidden]{display:none!important}html,body{margin:0;min-height:100%}body{background:var(--bg);color:var(--ink);font-family:"Microsoft YaHei","Segoe UI",system-ui,-apple-system,sans-serif;font-size:15px;line-height:1.55;transition:background var(--motion),color var(--motion)}button,input,textarea,a{font:inherit}button{cursor:pointer}a{color:inherit}:focus-visible{outline:3px solid rgba(216,97,69,.35);outline-offset:2px}
.topbar{background:var(--teal);color:#f7fbf6;border-bottom:4px solid var(--yellow)}.topbar-inner{width:min(1320px,calc(100% - 40px));min-height:72px;margin:auto;display:flex;align-items:center;justify-content:space-between;gap:20px}.brand{display:flex;align-items:center;gap:12px;min-width:0}.brand-mark{width:38px;height:38px;flex:0 0 38px;display:grid;place-items:center;background:var(--yellow);color:var(--teal-dark);border-radius:7px;font-size:20px;font-weight:900}.brand-name{margin:0;font-size:18px;line-height:1.1;font-weight:800;letter-spacing:.02em}.brand-sub{margin:3px 0 0;color:rgba(247,251,246,.72);font-size:12px}.topbar-actions{display:flex;align-items:center;gap:12px}.online{display:inline-flex;align-items:center;gap:7px;color:rgba(247,251,246,.86);font-size:13px}.online-dot{width:8px;height:8px;border-radius:50%;background:#a7df76;box-shadow:0 0 0 4px rgba(167,223,118,.14)}.theme-toggle{width:36px;height:36px;padding:0;display:grid;place-items:center;border:1px solid rgba(247,251,246,.24);border-radius:7px;background:transparent;color:#f7fbf6;transition:background var(--motion),border-color var(--motion)}.theme-toggle:hover{background:rgba(255,255,255,.12);border-color:rgba(255,255,255,.44)}
.workspace{width:min(1320px,calc(100% - 40px));margin:auto;padding:48px 0 64px;display:grid;grid-template-columns:minmax(0,1fr) 350px;gap:28px;align-items:start}.main-column{min-width:0}.intro{margin:0 0 28px;max-width:760px}.eyebrow{display:inline-flex;align-items:center;gap:8px;color:var(--coral);font-size:12px;font-weight:800;letter-spacing:.14em}.eyebrow:before{content:"";width:24px;height:2px;background:var(--coral)}.intro h1{margin:13px 0 10px;max-width:720px;font-size:clamp(34px,4.3vw,58px);line-height:1.1;letter-spacing:-.04em;font-weight:900}.intro h1 em{color:var(--coral);font-style:normal}.intro p{max-width:590px;margin:0;color:var(--muted);font-size:16px}
.panel{background:var(--paper);border:1px solid var(--line);border-radius:var(--r);box-shadow:var(--shadow);transition:background var(--motion),border-color var(--motion),box-shadow var(--motion)}.ingest-panel{padding:24px}.panel-heading{display:flex;align-items:flex-start;justify-content:space-between;gap:18px;margin-bottom:22px}.panel-kicker{margin:0 0 4px;color:var(--faint);font-size:11px;font-weight:800;letter-spacing:.12em;text-transform:uppercase}.panel-title{margin:0;font-size:20px;line-height:1.2;font-weight:800}.panel-note{margin:6px 0 0;color:var(--muted);font-size:13px}
.mode-switch{display:inline-flex;gap:3px;padding:3px;background:var(--soft);border:1px solid var(--line);border-radius:7px;flex-shrink:0}.mode-btn{min-height:32px;padding:0 13px;border:0;border-radius:5px;background:transparent;color:var(--muted);font-size:13px;font-weight:700;transition:background var(--motion),color var(--motion),box-shadow var(--motion)}.mode-btn.active{background:var(--teal);color:#fff;box-shadow:var(--small-shadow)}:root.dark .mode-btn.active,:root.dark .btn-teal{color:#173b37}
.field-label{display:block;margin-bottom:8px;color:var(--muted);font-size:13px;font-weight:700}.input-row{display:grid;grid-template-columns:minmax(0,1fr) 44px 116px;gap:9px}.input-wrap{min-width:0}.input-wrap input,.batch-input{width:100%;border:1px solid var(--strong);border-radius:6px;background:var(--soft);color:var(--ink);outline:none;transition:background var(--motion),border-color var(--motion),box-shadow var(--motion)}.input-wrap input{height:48px;padding:0 14px}.input-wrap input::placeholder,.batch-input::placeholder{color:var(--faint)}.input-wrap input:focus,.batch-input:focus{background:var(--paper);border-color:var(--coral);box-shadow:0 0 0 4px rgba(216,97,69,.12)}.batch-input{min-height:142px;padding:13px 14px;resize:vertical;line-height:1.6}
.icon-btn,.btn{display:inline-flex;align-items:center;justify-content:center;gap:7px;border-radius:6px;transition:background var(--motion),color var(--motion),border-color var(--motion),transform var(--motion),opacity var(--motion)}.icon-btn{width:44px;height:48px;padding:0;border:1px solid var(--strong);background:var(--paper);color:var(--teal)}.icon-btn:hover{border-color:var(--teal);background:var(--teal-soft)}.btn{min-height:42px;padding:0 15px;border:1px solid var(--line);background:var(--paper);color:var(--ink);font-size:13px;font-weight:800}.btn:hover{border-color:var(--strong);background:var(--soft)}.btn:disabled,.icon-btn:disabled{opacity:.48;cursor:not-allowed}.btn-primary{border-color:var(--coral);background:var(--coral);color:#fff}.btn-primary:hover:not(:disabled){border-color:var(--coral-dark);background:var(--coral-dark);transform:translateY(-1px)}.btn-teal{border-color:var(--teal);background:var(--teal);color:#fff}.btn-teal:hover:not(:disabled){border-color:var(--teal-dark);background:var(--teal-dark);transform:translateY(-1px)}.btn-quiet{background:transparent;border-color:transparent;color:var(--muted)}.btn-quiet:hover{color:var(--ink);background:var(--soft)}.batch-actions{display:flex;gap:8px;margin-top:12px}.input-hint{margin:10px 0 0;color:var(--faint);font-size:12px}.platform-strip{display:flex;flex-wrap:wrap;gap:8px;margin-top:22px;padding-top:18px;border-top:1px solid var(--line)}.platform-chip{display:inline-flex;align-items:center;gap:6px;min-height:25px;padding:0 9px;border:1px solid var(--line);border-radius:999px;background:var(--warm);color:var(--muted);font-size:12px}.platform-chip i{width:6px;height:6px;border-radius:50%;background:var(--chip)}
.state-row{display:flex;align-items:center;gap:9px;min-height:38px;margin-top:14px;padding:0 2px;color:var(--muted);font-size:13px}.spinner{width:16px;height:16px;border:2px solid var(--line);border-top-color:var(--coral);border-radius:50%;animation:spin .7s linear infinite}@keyframes spin{to{transform:rotate(360deg)}}.error-alert{display:flex;align-items:flex-start;gap:9px;margin-top:14px;padding:12px 14px;border:1px solid #f2b0a5;border-radius:6px;background:var(--danger-soft);color:var(--danger);font-size:13px}.error-alert svg{flex:0 0 auto;margin-top:2px}
.result-panel,.batch-panel{margin-top:28px;overflow:hidden}.result-layout{display:grid;grid-template-columns:minmax(0,1.03fr) minmax(280px,.97fr);min-height:320px}.result-video-wrap{min-height:320px;padding:22px;background:#142322;display:grid;place-items:center}.result-video-wrap video{display:block;width:100%;max-height:470px;aspect-ratio:16/10;object-fit:contain;border-radius:5px;background:#0b1514}.result-info{padding:25px;display:flex;flex-direction:column;min-width:0}.result-tag{display:inline-flex;align-self:flex-start;padding:4px 8px;background:var(--teal-soft);color:var(--teal);border-radius:4px;font-size:11px;font-weight:800}.result-title{margin:15px 0 7px;font-size:22px;line-height:1.35;font-weight:850;overflow-wrap:anywhere}.result-meta{margin:0;color:var(--muted);font-size:13px}.creator-row{display:flex;align-items:center;gap:10px;margin-top:22px}.avatar{width:38px;height:38px;border-radius:50%;border:1px solid var(--line);object-fit:cover;background:var(--soft)}.creator-label{color:var(--faint);font-size:11px}.creator-name{margin-top:1px;font-size:14px;font-weight:800}.result-stats{display:flex;gap:9px;margin-top:24px}.result-stat{min-width:88px;padding:10px 12px;border-top:2px solid var(--yellow);background:var(--warm)}.result-stat dt{color:var(--faint);font-size:11px}.result-stat dd{margin:2px 0 0;font-size:15px;font-weight:800}.result-actions{display:flex;flex-wrap:wrap;gap:8px;margin-top:auto;padding-top:24px}.result-actions .btn{text-decoration:none}
.section-heading{display:flex;align-items:center;justify-content:space-between;gap:12px;padding:20px 22px 16px;border-bottom:1px solid var(--line)}.section-heading h2{margin:0;font-size:17px;line-height:1.2}.section-heading p{margin:4px 0 0;color:var(--muted);font-size:12px}.batch-summary{color:var(--muted);font-size:12px}.batch-list{display:grid}.batch-empty{padding:28px 22px;color:var(--faint);font-size:13px}.batch-item{display:grid;grid-template-columns:108px minmax(0,1fr) auto;gap:13px;align-items:center;padding:14px 22px;border-bottom:1px solid var(--line)}.batch-item:last-child{border-bottom:0}.batch-thumb{width:108px;height:64px;object-fit:cover;border-radius:5px;background:var(--soft)}.batch-content{min-width:0}.batch-title{margin:0;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;font-size:14px;font-weight:800}.batch-meta{margin:3px 0 0;color:var(--muted);font-size:12px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.batch-actions{display:flex;flex-wrap:wrap;justify-content:flex-end;gap:6px;margin:0}.batch-actions .btn{min-height:34px;padding:0 10px;font-size:12px}.batch-item.is-loading .batch-thumb{background:var(--line);animation:pulse 1.3s ease-in-out infinite alternate}.batch-item.is-loading .batch-title{width:58%;height:16px;background:var(--line);color:transparent;border-radius:3px}@keyframes pulse{to{opacity:.55}}.batch-item.is-error{background:var(--coral-soft)}.batch-item.is-error .batch-title{color:var(--danger)}
.sidebar{display:grid;gap:16px;position:sticky;top:20px}.side-panel{padding:18px}.side-heading{display:flex;align-items:flex-start;justify-content:space-between;gap:10px;margin-bottom:15px}.side-heading h2{margin:0;font-size:17px}.side-heading p{margin:4px 0 0;color:var(--muted);font-size:12px}.count-badge{min-width:28px;height:24px;padding:0 7px;display:inline-grid;place-items:center;border-radius:4px;background:var(--yellow);color:var(--teal-dark);font-size:12px;font-weight:900}.history-list{display:grid;gap:8px}.history-empty{padding:28px 10px 22px;border-top:1px dashed var(--strong);text-align:center;color:var(--muted)}.history-empty-icon{width:40px;height:40px;margin:0 auto 10px;display:grid;place-items:center;border:1px solid var(--line);border-radius:6px;color:var(--coral);background:var(--warm)}.history-empty strong{display:block;color:var(--ink);font-size:13px}.history-empty span{display:block;margin-top:3px;font-size:12px}.history-entry{display:grid;grid-template-columns:62px minmax(0,1fr) auto;gap:9px;align-items:center;padding:8px;border:1px solid var(--line);border-radius:6px;background:var(--soft)}.history-thumb{width:62px;height:42px;object-fit:cover;border-radius:4px;background:var(--line)}.history-copy{min-width:0}.history-title{margin:0;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;font-size:12px;font-weight:800}.history-meta{margin:2px 0 0;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;color:var(--muted);font-size:11px}.history-actions{display:flex;gap:2px}.history-actions button{width:28px;height:28px;padding:0;display:grid;place-items:center;border:0;border-radius:4px;background:transparent;color:var(--muted)}.history-actions button:hover{background:var(--teal-soft);color:var(--teal)}.side-divider{height:1px;margin:18px 0;background:var(--line)}.quick-list{display:grid;gap:10px}.quick-row{display:flex;align-items:center;justify-content:space-between;gap:10px;color:var(--muted);font-size:13px}.quick-label{display:inline-flex;align-items:center;gap:8px}.quick-label svg{color:var(--coral)}.quick-value{color:var(--ink);font-weight:800}.clear-btn{min-height:28px;padding:0 8px;border:0;border-radius:4px;background:transparent;color:var(--muted);font-size:12px}.clear-btn:hover{background:var(--coral-soft);color:var(--coral-dark)}footer{width:min(1320px,calc(100% - 40px));margin:auto;padding:0 0 28px;color:var(--faint);font-size:12px}
@media(max-width:980px){.workspace{grid-template-columns:1fr}.sidebar{position:static;grid-template-columns:minmax(0,1.2fr) minmax(260px,.8fr);align-items:start}}@media(max-width:720px){.topbar-inner,.workspace,footer{width:min(100% - 28px,1320px)}.workspace{padding:32px 0 46px;gap:20px}.intro h1{font-size:36px}.ingest-panel{padding:18px}.panel-heading{flex-direction:column;gap:13px}.result-layout{grid-template-columns:1fr}.result-video-wrap{min-height:0;padding:14px}.result-info{padding:20px}.sidebar{grid-template-columns:1fr}}@media(max-width:520px){.topbar-inner{min-height:64px}.brand-sub,.online{display:none}.input-row{grid-template-columns:minmax(0,1fr) 44px}.input-row .btn-primary{grid-column:1/-1}.batch-item{grid-template-columns:76px minmax(0,1fr);padding:12px 14px}.batch-thumb{width:76px;height:50px}.batch-actions{grid-column:1/-1;justify-content:flex-start}.result-actions .btn{flex:1 1 calc(50% - 8px)}}
 .intro h1{max-width:900px;font-size:clamp(34px,3.8vw,52px)}
:root{--bg:#070d10;--paper:#101b1e;--soft:#142326;--warm:#17282a;--ink:#eaf7f2;--muted:#9db3ac;--faint:#6d8880;--line:#29413f;--strong:#3b5b55;--teal:#53dfbd;--teal-dark:#a0f6dd;--teal-soft:#183b36;--coral:#ff8064;--coral-dark:#ffad95;--coral-soft:#402622;--yellow:#f5cf73;--danger:#ff9a8b;--danger-soft:#432725;--shadow:0 18px 50px rgba(0,0,0,.28);--small-shadow:0 5px 18px rgba(0,0,0,.24)}
:root:not(.dark){--bg:#eef0eb;--paper:#fff;--soft:#f7f9f4;--warm:#fbfaf5;--ink:#1b2630;--muted:#68736e;--faint:#96a19b;--line:#d9ded7;--strong:#c3cbc2;--teal:#1b4a49;--teal-dark:#123b3b;--teal-soft:#e8f1ee;--coral:#d86145;--coral-dark:#ae452f;--coral-soft:#fff0eb;--yellow:#f5c85d;--danger:#b8443e;--danger-soft:#fff0ee;--shadow:0 14px 36px rgba(24,39,34,.08);--small-shadow:0 5px 16px rgba(24,39,34,.06)}
body{position:relative;isolation:isolate;overflow-x:hidden;background:var(--bg)}
body:before{content:"";position:fixed;inset:0;z-index:-1;pointer-events:none;opacity:.25;background-image:linear-gradient(rgba(83,223,189,.13) 1px,transparent 1px),linear-gradient(90deg,rgba(83,223,189,.13) 1px,transparent 1px);background-size:64px 64px;animation:grid-drift 24s linear infinite}
body:after{content:"";position:fixed;z-index:-1;left:-35vw;top:23%;width:32vw;height:1px;pointer-events:none;background:var(--teal);opacity:.45;box-shadow:0 170px 0 var(--coral),0 340px 0 var(--teal);animation:scan-drift 14s linear infinite}
@keyframes grid-drift{to{transform:translate3d(64px,64px,0)}}@keyframes scan-drift{0%{transform:translateX(0);opacity:0}12%{opacity:.42}88%{opacity:.42}100%{transform:translateX(440vw);opacity:0}}
.topbar{box-shadow:0 0 28px rgba(83,223,189,.13)}.online-dot{animation:status-pulse 2s ease-in-out infinite}@keyframes status-pulse{0%,100%{box-shadow:0 0 0 4px rgba(167,223,118,.12)}50%{box-shadow:0 0 0 8px rgba(167,223,118,.03)}}
.panel{backdrop-filter:blur(14px)}:root.dark .panel{background:rgba(16,27,30,.88)}:root.dark .ingest-panel{box-shadow:0 0 0 1px rgba(83,223,189,.04),var(--shadow)}:root.dark .result-video-wrap{background:#071211}
.brand-name{letter-spacing:.08em}
:root.dark .topbar{background:#0a171a;color:#eaf7f2}:root:not(.dark) .panel{background:var(--paper);border-color:var(--line);box-shadow:var(--shadow)}:root:not(.dark) .sidebar .panel{background:var(--paper)}
.topbar{position:relative;box-shadow:0 0 28px rgba(83,223,189,.13),0 1px 0 rgba(83,223,189,.25)}.topbar:after{content:"LIVE / SIGNAL ROUTER";position:absolute;right:28px;bottom:4px;color:rgba(83,223,189,.32);font:9px/1 "Cascadia Code","Consolas",monospace;letter-spacing:.18em}.brand-mark{border-radius:2px;clip-path:polygon(0 0,100% 0,100% 78%,78% 100%,0 100%);box-shadow:5px 5px 0 rgba(245,207,115,.16)}.brand-name:after{content:" / CONTROL";color:var(--teal);font:10px/1 "Cascadia Code","Consolas",monospace;letter-spacing:.12em}
.workspace{position:relative;width:min(1440px,calc(100% - 56px));grid-template-columns:88px minmax(0,1fr) 330px;gap:24px;padding-top:52px}.workspace:before{content:"INDEX\A\A01  INPUT\A\A02  RESULT\A\A03  EXPORT\A\A+  READY";white-space:pre;grid-column:1;grid-row:1;align-self:start;padding:18px 0 0 8px;border-left:1px solid rgba(83,223,189,.35);color:rgba(157,179,172,.6);font:10px/1.1 "Cascadia Code","Consolas",monospace;letter-spacing:.08em;writing-mode:horizontal-tb}.main-column{grid-column:2;grid-row:1}.sidebar{grid-column:3;grid-row:1;position:relative;top:0;padding-left:16px;border-left:1px solid rgba(83,223,189,.22)}.intro{position:relative;max-width:none;padding:0 0 24px 20px;border-left:2px solid var(--coral)}.intro:after{content:"01 / INGEST";position:absolute;right:6px;bottom:26px;color:var(--faint);font:10px/1 "Cascadia Code","Consolas",monospace;letter-spacing:.12em}.intro h1{max-width:940px;margin-top:10px;font-size:clamp(38px,4.5vw,66px);letter-spacing:-.06em}.intro p{max-width:690px;font-size:15px}.intro p:before{content:"// ";color:var(--coral);font-family:"Cascadia Code","Consolas",monospace}
.panel{position:relative;border-radius:2px;background:rgba(16,27,30,.9);border-color:rgba(83,223,189,.26);box-shadow:0 0 0 1px rgba(83,223,189,.035),0 20px 55px rgba(0,0,0,.28);overflow:hidden}.panel:after{content:"";position:absolute;inset:6px;pointer-events:none;border:1px solid rgba(83,223,189,.06);clip-path:polygon(0 0,22px 0,22px 1px,calc(100% - 22px) 1px,calc(100% - 22px) 0,100% 0,100% 22px,calc(100% - 1px) 22px,calc(100% - 1px) calc(100% - 22px),100% calc(100% - 22px),100% 100%,calc(100% - 22px) 100%,calc(100% - 22px) calc(100% - 1px),22px calc(100% - 1px),22px 100%,0 100%,0 calc(100% - 22px),1px calc(100% - 22px),1px 22px,0 22px)}.ingest-panel{min-height:360px;padding:28px}.ingest-panel:before{content:"";position:absolute;right:-58px;top:30px;width:300px;height:300px;border:1px solid rgba(83,223,189,.2);border-radius:50%;box-shadow:0 0 0 18px rgba(83,223,189,.025),0 0 0 38px rgba(216,97,69,.03),inset 0 0 0 28px rgba(83,223,189,.025);animation:signal-ring 12s linear infinite;pointer-events:none}.ingest-panel:after{content:"SIGNAL / READY";inset:auto 26px 22px auto;border:0;color:rgba(83,223,189,.45);font:10px/1 "Cascadia Code","Consolas",monospace;letter-spacing:.16em;clip-path:none}.ingest-panel>*{position:relative;z-index:1}@keyframes signal-ring{to{transform:rotate(360deg)}}
.panel-kicker,.eyebrow,.batch-summary,.quick-value{font-family:"Cascadia Code","Consolas",monospace}.panel-kicker{color:var(--teal)}.panel-title{letter-spacing:.02em}.panel-note{max-width:440px}.mode-switch{border-radius:2px;background:rgba(83,223,189,.04);border-color:rgba(83,223,189,.24)}.mode-btn{border-radius:1px}.mode-btn.active{background:var(--teal);color:#071412;border-radius:1px}.field-label{font-family:"Cascadia Code","Consolas",monospace;font-size:11px;letter-spacing:.1em;text-transform:uppercase;color:var(--teal)}.input-wrap input,.batch-input{border-radius:2px;background:rgba(5,13,15,.78);border-color:rgba(83,223,189,.3);font-size:14px}.input-wrap input:focus,.batch-input:focus{border-color:var(--teal);box-shadow:0 0 0 3px rgba(83,223,189,.12),0 0 26px rgba(83,223,189,.08)}.icon-btn{border-radius:2px;background:rgba(83,223,189,.06);border-color:rgba(83,223,189,.3)}.btn{border-radius:2px}.btn-primary{box-shadow:0 0 20px rgba(255,128,100,.14)}.platform-chip{border-radius:2px;background:rgba(83,223,189,.04);font-family:"Cascadia Code","Consolas",monospace;font-size:11px}.input-hint{font-family:"Cascadia Code","Consolas",monospace;font-size:11px}
.sidebar .panel{box-shadow:none;background:rgba(10,21,23,.78)}.side-heading h2,.section-heading h2{font-family:"Cascadia Code","Consolas",monospace;letter-spacing:.05em}.count-badge{border-radius:2px}.history-entry{border-radius:2px;background:rgba(83,223,189,.04);border-color:rgba(83,223,189,.2)}.history-actions button{border-radius:1px}.history-empty{border-top-style:solid}.quick-row{font-family:"Cascadia Code","Consolas",monospace;font-size:12px}.result-panel,.batch-panel{border-color:rgba(255,128,100,.3)}.result-video-wrap{background:#050b0c}.result-tag{border-radius:1px;font-family:"Cascadia Code","Consolas",monospace}.result-stat{border-top-width:1px;background:rgba(245,207,115,.06)}footer{width:min(1440px,calc(100% - 56px));font-family:"Cascadia Code","Consolas",monospace}
@media(max-width:1100px){.workspace{grid-template-columns:58px minmax(0,1fr) 300px;gap:18px}.workspace:before{font-size:9px}.sidebar{padding-left:12px}}
@media(max-width:980px){.workspace{width:min(1320px,calc(100% - 40px));grid-template-columns:1fr}.workspace:before{display:none}.main-column,.sidebar{grid-column:1;grid-row:auto}.sidebar{padding-left:0;border-left:0}.intro:after{right:0}}
@media(max-width:720px){.workspace,footer{width:min(100% - 28px,1320px)}.workspace{padding-top:34px}.topbar:after{display:none}.ingest-panel:before{right:-150px;top:120px;opacity:.55}.intro h1{font-size:38px}}
/* Calm neutral theme: keep attention on the parser instead of the background. */
:root{--bg:#f3f5f7;--paper:#ffffff;--soft:#f7f8fa;--warm:#fbfcfd;--ink:#1d2935;--muted:#667482;--faint:#8b98a5;--line:#dfe5ea;--strong:#bdc8d1;--teal:#243b53;--teal-dark:#162b42;--teal-soft:#edf2f7;--coral:#c65d46;--coral-dark:#a84b38;--coral-soft:#fff1ed;--yellow:#d7a844;--danger:#b64b45;--danger-soft:#fff0ef;--shadow:0 10px 28px rgba(29,41,53,.08);--small-shadow:0 4px 12px rgba(29,41,53,.07)}
:root.dark{--bg:#151a20;--paper:#202831;--soft:#252f39;--warm:#29343f;--ink:#eef2f5;--muted:#b3bec8;--faint:#82909c;--line:#36424d;--strong:#4a5965;--teal:#a9c5df;--teal-dark:#d2e2f0;--teal-soft:#2b3b4a;--coral:#e98268;--coral-dark:#ffad97;--coral-soft:#49302c;--yellow:#e2bd62;--danger:#ff9d91;--danger-soft:#4b2e2d;--shadow:0 12px 30px rgba(0,0,0,.2);--small-shadow:0 4px 12px rgba(0,0,0,.18)}
body{background:var(--bg);}
body:before,body:after{display:none!important}
.workspace{width:min(1320px,calc(100% - 40px));grid-template-columns:minmax(0,1fr) 350px;gap:28px;padding-top:48px}
.workspace:before{display:none}
.main-column{grid-column:auto;grid-row:auto}
.sidebar{grid-column:auto;grid-row:auto;position:sticky;top:20px;padding-left:0;border-left:0}
.intro{padding:0;border-left:0;max-width:760px}
.intro:after{display:none}
.intro h1{max-width:720px;margin-top:13px;font-size:clamp(34px,4.3vw,58px);letter-spacing:0}
.intro p{max-width:590px;font-size:16px}
.intro p:before{content:none}
.panel{border-radius:8px;background:var(--paper);border-color:var(--line);box-shadow:var(--shadow);overflow:hidden}
.panel:after,.ingest-panel:before{display:none}
.topbar{box-shadow:0 1px 0 rgba(36,59,83,.12)}
:root.dark .topbar{background:var(--teal);color:var(--ink);box-shadow:0 1px 0 rgba(169,197,223,.16)}
:root.dark .panel{background:var(--paper);border-color:var(--line);box-shadow:var(--shadow)}
:root.dark .result-video-wrap{background:#0f151b}
.topbar:after{display:none}
.brand-mark{box-shadow:none;clip-path:none}
.brand-name{letter-spacing:.02em}
.brand-name:after{content:none}
.ingest-panel{min-height:0;padding:24px}
.ingest-panel:after{content:none}
.mode-switch{border-radius:7px;background:var(--soft);border-color:var(--line)}
.mode-btn{border-radius:5px}
.mode-btn.active{background:var(--teal);color:#fff;border-radius:5px}
.input-wrap input,.batch-input{border-radius:6px;background:var(--soft);border-color:var(--strong)}
.icon-btn,.btn{border-radius:6px}
.platform-chip{border-radius:999px;background:var(--warm);font-family:inherit;font-size:12px}
.sidebar .panel{background:var(--paper);box-shadow:var(--shadow)}
.history-entry{border-radius:6px;background:var(--soft);border-color:var(--line)}
.result-panel,.batch-panel{border-color:var(--line)}
@media(max-width:1100px){.workspace{grid-template-columns:minmax(0,1fr) 300px;gap:18px}.sidebar{padding-left:0}}
@media(max-width:980px){.workspace{grid-template-columns:1fr}.main-column,.sidebar{grid-column:auto;grid-row:auto}.sidebar{position:static}}
</style>
</head>
<body>
<header class="topbar"><div class="topbar-inner"><div class="brand"><span class="brand-mark" aria-hidden="true">去</span><div><p class="brand-name">去水印解析</p><p class="brand-sub">短视频无水印工作台</p></div></div><div class="topbar-actions"><span class="online"><i class="online-dot"></i>服务在线</span><button id="theme-toggle" class="theme-toggle" type="button" title="切换主题" aria-label="切换主题"></button></div></div></header>
<main class="workspace">
  <div class="main-column">
    <section class="intro" aria-labelledby="page-title"><span class="eyebrow">VIDEO WORKSPACE / 01</span><h1 id="page-title">分享链接，<em>直接变成</em>可用视频。</h1><p>粘贴短视频分享链接，快速整理出无水印视频。解析结果、下载和最近记录都在同一个工作区完成。</p></section>
    <section class="panel ingest-panel" aria-label="视频解析入口">
      <div class="panel-heading"><div><p class="panel-kicker">Import link</p><h2 class="panel-title">从一个链接开始</h2><p class="panel-note">支持公开分享链接，不需要登录第三方平台。</p></div><div class="mode-switch" role="group" aria-label="解析模式"><button id="single-mode-btn" class="mode-btn active" type="button" aria-pressed="true">单个解析</button><button id="batch-mode-btn" class="mode-btn" type="button" aria-pressed="false">批量处理</button></div></div>
      <div id="single-panel"><label id="mode-label" class="field-label" for="video-url">视频分享链接</label><div class="input-row"><div class="input-wrap"><input id="video-url" type="url" placeholder="粘贴抖音、快手、B站、小红书等链接" autocomplete="off" spellcheck="false"></div><button id="paste-btn" class="icon-btn" type="button" title="从剪贴板粘贴" aria-label="从剪贴板粘贴"><svg width="19" height="19" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="8" y="3" width="8" height="4" rx="1"></rect><path d="M16 5h2a2 2 0 0 1 2 2v12a2 2 0 0 1-2 2H6a2 2 0 0 1-2-2V7a2 2 0 0 1 2-2h2"></path></svg></button><button id="parse-btn" class="btn btn-primary" type="button"><svg width="17" height="17" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M5 12h14"></path><path d="m13 6 6 6-6 6"></path></svg><span>开始解析</span></button></div><p class="input-hint">小提示：也可以直接粘贴包含文字的整段分享文案，系统会自动提取链接。</p></div>
      <div id="batch-panel" hidden><label class="field-label" for="batch-input">每行放一个视频链接</label><textarea id="batch-input" class="batch-input" rows="5" placeholder="https://...&#10;https://...&#10;https://..." autocomplete="off" spellcheck="false" aria-label="批量视频链接"></textarea><div class="batch-actions"><button id="batch-parse-btn" class="btn btn-primary" type="button"><svg width="17" height="17" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M8 6h13"></path><path d="M8 12h13"></path><path d="M8 18h13"></path><path d="M3 6h.01"></path><path d="M3 12h.01"></path><path d="M3 18h.01"></path></svg><span>开始批量处理</span></button><button id="batch-stop-btn" class="btn btn-quiet" type="button" hidden>停止处理</button></div></div>
      <div class="platform-strip" aria-label="支持平台"><span class="platform-chip" style="--chip:#2d6cdf"><i></i>抖音</span><span class="platform-chip" style="--chip:#10a77a"><i></i>快手</span><span class="platform-chip" style="--chip:#e86d94"><i></i>B站</span><span class="platform-chip" style="--chip:#e64555"><i></i>小红书</span><span class="platform-chip" style="--chip:#f19a42"><i></i>皮皮虾</span><span class="platform-chip" style="--chip:#5e83d7"><i></i>微博</span><span class="platform-chip" style="--chip:#4d9d91"><i></i>视频号</span><span class="platform-chip" style="--chip:#8d6fc1"><i></i>更多平台</span></div>
      <div id="loading" class="state-row" aria-live="polite" hidden><span class="spinner" aria-hidden="true"></span><span id="loading-text">正在读取视频信息…</span></div><div id="batch-progress" class="state-row" aria-live="polite" hidden><span class="spinner" aria-hidden="true"></span><span id="batch-progress-text"></span></div>
      <div id="error" class="error-alert" role="alert" aria-live="assertive" hidden><svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><circle cx="12" cy="12" r="9"></circle><path d="M12 8v5"></path><path d="M12 16h.01"></path></svg><span id="error-text"></span></div>
    </section>
    <section id="result" class="panel result-panel" hidden aria-label="解析结果"><div class="result-layout"><div class="result-video-wrap"><video id="result-video" controls playsinline preload="metadata"></video></div><div class="result-info"><span id="result-platform" class="result-tag">解析完成</span><h2 id="result-title" class="result-title"></h2><p id="result-meta" class="result-meta"></p><div class="creator-row"><img id="result-avatar" class="avatar" alt="" hidden><div><div class="creator-label">发布作者</div><div id="result-author" class="creator-name"></div></div></div><dl class="result-stats"><div class="result-stat"><dt>点赞</dt><dd id="result-like">-</dd></div><div class="result-stat"><dt>发布时间</dt><dd id="result-time">-</dd></div></dl><div class="result-actions"><a id="download-btn" class="btn btn-primary" download target="_blank" rel="noopener"><svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M12 3v12"></path><path d="m7 10 5 5 5-5"></path><path d="M5 21h14"></path></svg><span>下载视频</span></a><button id="copy-btn" class="btn" type="button"><svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="11" height="11" rx="2"></rect><path d="M5 15H4a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h8a2 2 0 0 1 2 2v1"></path></svg><span>复制链接</span></button><button id="copy-text-btn" class="btn" type="button"><svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"></path><path d="M14 2v6h6"></path><path d="M8 13h8"></path><path d="M8 17h5"></path></svg><span>复制文案</span></button><a id="open-btn" class="btn btn-quiet" target="_blank" rel="noopener"><svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M14 3h7v7"></path><path d="M10 14 21 3"></path><path d="M21 14v5a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h5"></path></svg><span>打开视频</span></a></div></div></div></section>
    <section id="batch-results" class="panel batch-panel" hidden aria-label="批量解析结果"><div class="section-heading"><div><h2>批量处理结果</h2><p>完成的项目可以直接播放、下载或复制文案。</p></div><span id="batch-summary" class="batch-summary"></span></div><div id="batch-list" class="batch-list"></div><div id="batch-empty" class="batch-empty" hidden>还没有批量任务。</div></section>
  </div>
  <aside class="sidebar"><section id="history" class="panel side-panel" aria-label="最近解析"><div class="side-heading"><div><h2>最近处理</h2><p>只保存在当前浏览器</p></div><span id="history-count" class="count-badge">0</span></div><div id="history-list" class="history-list"></div><div id="history-empty" class="history-empty"><div class="history-empty-icon"><svg width="21" height="21" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M4 5h16v14H4z"></path><path d="M8 9h8"></path><path d="M8 13h5"></path></svg></div><strong>这里还没有记录</strong><span>解析完成后会自动出现在这里</span></div><div class="side-divider"></div><button id="clear-history-btn" class="clear-btn" type="button"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><polyline points="3 6 5 6 21 6"></polyline><path d="M19 6v14a2 2 0 0 1-2-2H7a2 2 0 0 1-2-2V6m3 0V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2"></path></svg> 清空记录</button></section><section class="panel side-panel" aria-label="工作台信息"><div class="side-heading"><div><h2>工作台</h2><p>让每次整理更顺手</p></div></div><div class="quick-list"><div class="quick-row"><span class="quick-label"><svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><circle cx="12" cy="12" r="9"></circle><path d="M12 7v5l3 2"></path></svg>单个解析</span><strong class="quick-value">即时</strong></div><div class="quick-row"><span class="quick-label"><svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M8 6h13"></path><path d="M8 12h13"></path><path d="M8 18h13"></path><path d="M3 6h.01"></path><path d="M3 12h.01"></path><path d="M3 18h.01"></path></svg>批量处理</span><strong class="quick-value">最多 3 路</strong></div><div class="quick-row"><span class="quick-label"><svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M12 3v18"></path><path d="M3 12h18"></path></svg>记录方式</span><strong class="quick-value">本地保存</strong></div></div></section></aside>
</main>
<footer>去水印解析 · 仅用于个人学习与研究</footer>
<script>
const $=s=>document.querySelector(s),input=$('#video-url'),parseBtn=$('#parse-btn'),pasteBtn=$('#paste-btn'),singleModeBtn=$('#single-mode-btn'),batchModeBtn=$('#batch-mode-btn'),singlePanel=$('#single-panel'),batchPanel=$('#batch-panel'),batchInput=$('#batch-input'),batchParseBtn=$('#batch-parse-btn'),batchStopBtn=$('#batch-stop-btn'),loading=$('#loading'),loadingText=$('#loading-text'),batchProgress=$('#batch-progress'),batchProgressText=$('#batch-progress-text'),errorBox=$('#error'),errorText=$('#error-text'),result=$('#result'),video=$('#result-video'),avatar=$('#result-avatar'),titleEl=$('#result-title'),metaEl=$('#result-meta'),authorEl=$('#result-author'),likeEl=$('#result-like'),timeEl=$('#result-time'),platformEl=$('#result-platform'),downloadBtn=$('#download-btn'),copyBtn=$('#copy-btn'),copyTextBtn=$('#copy-text-btn'),openBtn=$('#open-btn'),historyList=$('#history-list'),historyEmpty=$('#history-empty'),historyCount=$('#history-count'),clearHistoryBtn=$('#clear-history-btn'),batchSection=$('#batch-results'),batchList=$('#batch-list'),batchEmpty=$('#batch-empty'),batchSummary=$('#batch-summary'),themeToggle=$('#theme-toggle'),modeLabel=$('#mode-label');
const HISTORY_KEY='watermark-parse-history-v1',HISTORY_LIMIT=20,URL_PATTERN=/https?:\/\/[^\s"'<>，。；：！？【】（）《》]+/i;
const PLAY_ICON='<svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><polygon points="6 3 20 12 6 21 6 3"></polygon></svg>',DOWNLOAD_ICON='<svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M12 3v12"></path><path d="m7 10 5 5 5-5"></path><path d="M5 21h14"></path></svg>',COPY_ICON='<svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="11" height="11" rx="2"></rect><path d="M5 15H4a2 2 0 0 1-2-2V5a2 2 0 0 1 2 2v1"></path></svg>',TRASH_ICON='<svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><polyline points="3 6 5 6 21 6"></polyline><path d="M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6m3 0V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2"></path></svg>';
let ignoreMediaError=false,currentResult=null,batchItems=[],batchRunning=false,batchCancelRequested=false;
function extractUrl(text){const m=String(text).match(URL_PATTERN);return m?m[0].replace(/[),.。]+$/,''):String(text).trim()}
function platformName(url){const h=(String(url).match(/^https?:\/\/([^/]+)/i)||[])[1]||'';if(h.includes('douyin.com'))return'抖音';if(h.includes('kuaishou.com')||h.includes('kuaishou.cn'))return'快手';if(h.includes('bilibili.com')||h.includes('b23.tv'))return'B站';if(h.includes('xiaohongshu.com')||h.includes('xhslink.com'))return'小红书';if(h.includes('pipix.com'))return'皮皮虾';if(h.includes('weishi.qq.com'))return'微视';if(h.includes('weibo.com'))return'微博';if(h.includes('izuiyou.com')||h.includes('xiaochuankeji.cn'))return'最右';if(h.includes('ippzone.com')||h.includes('pipigx.com'))return'皮皮搞笑';if(h.includes('channels.weixin.qq.com'))return'视频号';if(h.includes('ixigua.com'))return'西瓜视频';return'短视频'}
function formatTime(v){if(!v&&v!==0)return'';if(typeof v==='number'||/^\\d{10}$/.test(String(v))){const s=typeof v==='number'?v:parseInt(v,10);if(s<1000000000)return'';const d=new Date(s*1000);if(Number.isNaN(d.getTime()))return'';return d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0')}return String(v)}
function formatCount(v){if(v===undefined||v===null||v==='')return'-';const n=Number(v);return Number.isFinite(n)?new Intl.NumberFormat('zh-CN',{notation:'compact',maximumFractionDigits:1}).format(n):String(v)}
function esc(v){return String(v??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#39;')}
function mediaUrl(url){return'index.php?action=media&url='+encodeURIComponent(url)}function buildDownloadUrl(url,title){return mediaUrl(url)+'&download=1&filename='+encodeURIComponent((title||'video')+'.mp4')}
function setMode(mode){const one=mode==='single';singlePanel.hidden=!one;batchPanel.hidden=one;singleModeBtn.classList.toggle('active',one);batchModeBtn.classList.toggle('active',!one);singleModeBtn.setAttribute('aria-pressed',String(one));batchModeBtn.setAttribute('aria-pressed',String(!one));modeLabel.textContent=one?'视频分享链接':'每行放一个视频链接';(one?input:batchInput).focus()}
function setLoading(on){loading.hidden=!on;parseBtn.disabled=on;loadingText.textContent=on?'正在读取视频信息…':''}function showError(m){errorText.textContent=m||'解析失败，请稍后再试';errorBox.hidden=false}function hideError(){errorBox.hidden=true;errorText.textContent=''}
function hideResult(){result.hidden=true;ignoreMediaError=true;currentResult=null;video.removeAttribute('src');video.removeAttribute('poster');video.load()}
async function requestParse(url){const r=await fetch('api/v1/parse',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({url})}),j=await r.json().catch(()=>null);if(!r.ok||!j||!j.success||!j.data||!j.data.url)throw new Error(j&&j.message||'解析失败，请稍后再试');return{url,data:j.data}}
async function parseUrlIntoResult(url){hideError();hideResult();setLoading(true);try{const item=await requestParse(url);renderResult(item.data,item.url);addHistory(item);renderHistory();result.scrollIntoView({behavior:'smooth',block:'start'})}catch(e){showError(e.message||'解析失败，请稍后再试')}finally{setLoading(false)}}
async function parseVideo(){const raw=input.value.trim();if(!raw){showError('请先粘贴一个视频分享链接');input.focus();return}const url=extractUrl(raw);if(!/^https?:\/\//i.test(url)){showError('请输入有效的视频链接');return}await parseUrlIntoResult(url)}
function renderResult(data,raw){const vu=data.url||'',cover=data.cover||'';ignoreMediaError=false;currentResult={url:raw,data};video.src=mediaUrl(vu);if(cover)video.poster=mediaUrl(cover);else video.removeAttribute('poster');titleEl.textContent=data.title||'未命名视频';authorEl.textContent=data.author||'未知作者';platformEl.textContent=platformName(raw)+' · 解析完成';metaEl.textContent=[platformName(raw),formatTime(data.time)].filter(Boolean).join(' · ');likeEl.textContent=formatCount(data.like);timeEl.textContent=formatTime(data.time)||'-';if(data.avatar){avatar.src=mediaUrl(data.avatar);avatar.hidden=false}else{avatar.removeAttribute('src');avatar.hidden=true}downloadBtn.href=buildDownloadUrl(vu,data.title);downloadBtn.setAttribute('download',(data.title||'video')+'.mp4');openBtn.href=mediaUrl(vu);result.hidden=false}
function loadHistory(){try{const x=JSON.parse(localStorage.getItem(HISTORY_KEY)||'[]');return Array.isArray(x)?x:[]}catch(e){return[]}}function saveHistory(x){localStorage.setItem(HISTORY_KEY,JSON.stringify(x))}function addHistory(item){const list=loadHistory().filter(x=>x.rawUrl!==item.url);list.unshift({rawUrl:item.url,title:item.data.title||'',author:item.data.author||'',like:item.data.like??0,time:item.data.time??0,cover:item.data.cover||'',videoUrl:item.data.url||'',savedAt:Date.now()});saveHistory(list.slice(0,HISTORY_LIMIT))}function removeHistory(i){const list=loadHistory();list.splice(i,1);saveHistory(list);renderHistory()}
function historyItemHtml(item,i){const t=item.cover?mediaUrl(item.cover):'';return'<article class="history-entry" data-index="'+i+'"><img class="history-thumb" src="'+esc(t)+'" alt="" loading="lazy"><div class="history-copy"><h3 class="history-title">'+esc(item.title||'未命名视频')+'</h3><p class="history-meta">'+esc([platformName(item.rawUrl),formatTime(item.time)].filter(Boolean).join(' · '))+'</p></div><div class="history-actions"><button type="button" data-action="reparse" title="重新解析" aria-label="重新解析">'+PLAY_ICON+'</button><button type="button" data-action="copy" title="复制链接" aria-label="复制链接">'+COPY_ICON+'</button><button type="button" data-action="delete" title="删除记录" aria-label="删除记录">'+TRASH_ICON+'</button></div></article>'}
function renderHistory(){const list=loadHistory();historyCount.textContent=String(list.length);historyEmpty.hidden=list.length>0;historyList.innerHTML=list.map(historyItemHtml).join('')}
function setBatchRunning(on){batchRunning=on;batchParseBtn.disabled=on;batchStopBtn.hidden=!on;batchProgress.hidden=!on;batchParseBtn.querySelector('span').textContent=on?'处理中…':'开始批量处理'}function updateBatchSummary(){const ok=batchItems.filter(x=>x&&x.data).length,fail=batchItems.filter(x=>x&&x.error).length;batchSummary.textContent=[ok?'成功 '+ok:'',fail?'失败 '+fail:''].filter(Boolean).join(' · ')}
function batchItemHtml(item,i){if(item.loading)return'<article class="batch-item is-loading" data-index="'+i+'"><div class="batch-thumb"></div><div class="batch-content"><h3 class="batch-title">处理中</h3><p class="batch-meta">正在读取视频信息…</p></div><div class="batch-actions"><span class="batch-meta">请稍候</span></div></article>';if(item.error)return'<article class="batch-item is-error" data-index="'+i+'"><div class="batch-content"><h3 class="batch-title">'+esc(item.url)+'</h3><p class="batch-meta">'+esc(item.error)+'</p></div><div class="batch-actions"><button class="btn" type="button" data-action="retry">重试</button></div></article>';const d=item.data,t=d.cover?mediaUrl(d.cover):'';return'<article class="batch-item" data-index="'+i+'"><img class="batch-thumb" src="'+esc(t)+'" alt="" loading="lazy"><div class="batch-content"><h3 class="batch-title">'+esc(d.title||'未命名视频')+'</h3><p class="batch-meta">'+esc(platformName(item.url))+' · '+esc(d.author||'未知作者')+' · 点赞 '+esc(formatCount(d.like))+'</p></div><div class="batch-actions"><button class="btn" type="button" data-action="play">'+PLAY_ICON+'播放</button><a class="btn" href="'+esc(buildDownloadUrl(d.url,d.title))+'" download="'+esc((d.title||'video')+'.mp4')+'" target="_blank" rel="noopener">'+DOWNLOAD_ICON+'下载</a><button class="btn" type="button" data-action="copy">'+COPY_ICON+'复制</button></div></article>'}
function renderBatchList(){batchEmpty.hidden=batchItems.length>0;batchList.innerHTML=batchItems.map(batchItemHtml).join('');updateBatchSummary()}
async function parseBatch(){const urls=batchInput.value.split(/\n/).map(extractUrl).map(x=>x.trim()).filter(x=>/^https?:\/\//i.test(x)).filter((x,i,a)=>a.indexOf(x)===i);if(!urls.length){showError('请先粘贴至少一个有效的视频链接');return}hideError();batchItems=urls.map(url=>({url,loading:true}));batchCancelRequested=false;batchSection.hidden=false;renderBatchList();setBatchRunning(true);let done=0,next=0;async function worker(){while(!batchCancelRequested){const i=next++;if(i>=urls.length)return;const url=urls[i];try{batchItems[i]=await requestParse(url);addHistory(batchItems[i])}catch(e){batchItems[i]={url,error:e.message||'解析失败'}}done++;batchProgressText.textContent='正在处理 '+done+'/'+urls.length;renderBatchList()}}await Promise.all(Array.from({length:Math.min(3,urls.length)},()=>worker()));if(batchCancelRequested)batchItems=batchItems.map(x=>x&&x.loading?{url:x.url,error:'已停止处理'}:x);renderBatchList();renderHistory();setBatchRunning(false);batchProgressText.textContent=batchCancelRequested?'已停止':'已完成 '+urls.length+' 项';batchSection.scrollIntoView({behavior:'smooth',block:'start'})}
async function retryBatchItem(i){const old=batchItems[i];if(!old||batchRunning)return;batchItems[i]={url:old.url,loading:true};renderBatchList();try{batchItems[i]=await requestParse(old.url);addHistory(batchItems[i])}catch(e){batchItems[i]={url:old.url,error:e.message||'解析失败'}}renderBatchList();renderHistory()}
async function copyText(text){try{await navigator.clipboard.writeText(text)}catch(e){const t=document.createElement('textarea');t.value=text;t.style.position='fixed';t.style.opacity='0';document.body.appendChild(t);t.select();document.execCommand('copy');t.remove()}}function flashButton(b,text){const s=b.querySelector('span');if(!s)return;const old=s.textContent;s.textContent=text;setTimeout(()=>s.textContent=old,1200)}function buildShareText(x){return[x.data.title||'未命名视频',platformName(x.url),'无水印链接：'+buildDownloadUrl(x.data.url,x.data.title)].join('\\n')}
historyList.addEventListener('click',async e=>{const card=e.target.closest('.history-entry'),a=e.target.closest('[data-action]');if(!card||!a)return;const item=loadHistory()[Number(card.dataset.index)];if(!item)return;const action=a.dataset.action;if(action==='reparse'){setMode('single');input.value=item.rawUrl;await parseUrlIntoResult(item.rawUrl)}if(action==='copy'){await copyText(item.rawUrl);a.innerHTML='✓';setTimeout(()=>a.innerHTML=COPY_ICON,1000)}if(action==='delete')removeHistory(Number(card.dataset.index))});clearHistoryBtn.addEventListener('click',()=>{saveHistory([]);renderHistory()});
batchList.addEventListener('click',async e=>{const card=e.target.closest('.batch-item'),a=e.target.closest('[data-action]');if(!card||!a)return;const item=batchItems[Number(card.dataset.index)];if(!item)return;if(a.dataset.action==='play'&&item.data){setMode('single');input.value=item.url;await parseUrlIntoResult(item.url)}if(a.dataset.action==='copy'&&item.data){await copyText(buildShareText(item));a.textContent='已复制';setTimeout(()=>{a.innerHTML=COPY_ICON+'复制'},1000)}if(a.dataset.action==='retry')await retryBatchItem(Number(card.dataset.index))});
parseBtn.addEventListener('click',parseVideo);input.addEventListener('keydown',e=>{if(e.key==='Enter')parseVideo()});batchParseBtn.addEventListener('click',parseBatch);batchStopBtn.addEventListener('click',()=>{batchCancelRequested=true;batchProgressText.textContent='正在停止…'});batchInput.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key==='Enter')parseBatch()});singleModeBtn.addEventListener('click',()=>setMode('single'));batchModeBtn.addEventListener('click',()=>setMode('batch'));pasteBtn.addEventListener('click',async()=>{try{const text=await navigator.clipboard.readText(),target=singlePanel.hidden?batchInput:input;target.value=extractUrl(text);target.focus()}catch(e){showError('无法读取剪贴板，请手动粘贴')}});copyBtn.addEventListener('click',async()=>{if(currentResult&&downloadBtn.href){await copyText(downloadBtn.href);flashButton(copyBtn,'已复制')}});copyTextBtn.addEventListener('click',async()=>{if(currentResult){await copyText(buildShareText(currentResult));flashButton(copyTextBtn,'已复制')}});video.addEventListener('error',()=>{if(!ignoreMediaError)showError('视频播放失败，源站链接可能已失效或暂时禁止访问。')});
function applyTheme(theme){document.documentElement.classList.toggle('dark',theme==='dark');themeToggle.innerHTML=theme==='dark'?'<svg width="17" height="17" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><circle cx="12" cy="12" r="4"></circle><path d="M12 2v2"></path><path d="M12 20v2"></path><path d="m4.93 4.93 1.41 1.41"></path><path d="m17.66 17.66 1.41 1.41"></path><path d="M2 12h2"></path><path d="M20 12h2"></path></svg>':'<svg width="17" height="17" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M20.5 14.7A8.5 8.5 0 0 1 9.3 3.5 8.5 8.5 0 1 0 20.5 14.7z"></path></svg>';themeToggle.title=theme==='dark'?'切换浅色主题':'切换深色主题';themeToggle.setAttribute('aria-label',themeToggle.title);localStorage.setItem('watermark-parse-theme-v2',theme)}function preferredTheme(){const saved=localStorage.getItem('watermark-parse-theme-v2');return saved==='dark'||saved==='light'?saved:'dark'}themeToggle.addEventListener('click',()=>applyTheme(document.documentElement.classList.contains('dark')?'light':'dark'));applyTheme(preferredTheme());renderHistory();
</script>
</body>
</html>
